# Generated by Django 5.0.6 on 2024-06-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotoo', '0002_course_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='image_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
