# Generated by Django 5.0.6 on 2024-06-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotoo', '0004_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_path',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
