# Generated by Django 5.0.6 on 2024-06-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotoo', '0005_remove_course_image_path_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
