# Generated by Django 5.0.6 on 2024-06-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotoo', '0006_remove_course_image_course_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
